<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Statistic;
use Doctrine\ORM\EntityRepository;

/**
 * StatisticRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class StatisticRepository extends EntityRepository
{
    const STATISTIC_NUMBER_VIEWS = 'number_views';

    public function getNumberViews()
    {
        /** @var Statistic $statistic */
        $statistic = $this->findOneBy(array('name' => self::STATISTIC_NUMBER_VIEWS));

        if (!$statistic) {
            return 0;
        }

        return $statistic->getIntegerValue();
    }

    public function addView()
    {
        $statistic = $this->findOneBy(array('name' => self::STATISTIC_NUMBER_VIEWS));

        if (!$statistic) {
            $statistic = new Statistic();
            $statistic->setName(self::STATISTIC_NUMBER_VIEWS);
            $statistic->setValue(0);
        }

        $statistic->setValue($statistic->getIntegerValue() + 1);

        $this->getEntityManager()->persist($statistic);
        $this->getEntityManager()->flush($statistic);
    }
}
