services:
  imagethread.image_manager:
    class: AppBundle\Manager\ImageManager
    arguments:
      - "%web_dir%"
      - "%images_dir%"
  imagethread.form.type.post:
    class: AppBundle\Form\Type\PostType
    tags:
      - { name: form.type }
  app.twig_extension:
      class: AppBundle\Twig\AppExtension
      public: false
      arguments:
        - '@imagethread.image_manager'
        - '@doctrine.orm.entity_manager'
      tags:
          - { name: twig.extension }